# Import required modules
from database.run_sql import run_sql
from models.classes import Pet, Vet, Note
import repositories.pet_repository as PR
import repositories.vet_repository as VR

# CRUD FUNCTIONS

# FUNCTION: save(item)
# This function is used to save a note to the database
def save(note):
    # Create the SQL query && input data before running it
    sql = "INSERT INTO note (date, note_text, pet_id, vet_id) VALUES (%s, %s, %s, %s) RETURNING id"
    values = [note.date, note.note_text, note.pet.id, note.vet.id]
    result = run_sql(sql, values)

    # Set the note objects ID to the ID generated by the database
    note.id = result[0]['id']
    return note

# FUNCTION: select_all()
# This function is used to select all of the notes from the database and create python objects
# using the data so they can be displayed
def select_all():
    # Create list of note objects and set == empty list
    notes = []

    # Create the SQL query && input data before running it
    sql = "SELECT * FROM note"
    results = run_sql(sql)

    # Loop through all the results and append the objects to a list
    for row in results:
        # Get the objects to create the note object
        pet = PR.select(row['pet_id'])
        vet = VR.select(row['vet_id'])

        # Create new note object && append to notes list
        new_note = Note(row['date'], row['note_text'], pet, vet, row['id'])
        notes.append(new_note)

    return notes

# FUNCTION: select(item_id)
# This function is used to select a specific note by its ID in the database to be able to create an object
# that can be displayed
def select(note_id):
    # Create the SQL query, pass in the data and run it
    sql = "SELECT * FROM note WHERE id = %s"
    values = [note_id]
    result = run_sql(sql, values)

    # Create object if data is found in the database
    if len(result) > 0:
        pet = PR.select(result[0]['pet_id'])
        vet = VR.select(result[0]['vet_id'])
        new_note = Note(result[0]['date'], result[0]['note_text'], pet, vet)
    
    return new_note

# FUNCTION: delete(item_id)
# This function is used to delete a specific item from the database using its id
def delete(note_id):
    # Create the SQL query, pass in the data and run it
    sql = "DELETE FROM note WHERE id = %s"
    values = [note_id]
    run_sql(sql, values)

# FUNCTION: delete_all()
# This function is used to delete all data from the table that coresponds to the class it is run from
def delete_all():
    # Create SQL query and run it
    sql = "DELETE FROM note"
    run_sql(sql)

# FUNCTION: update(item_id)
# This function is used to update data within the database
def update(note):
    # Create SQL query, pass in the data and run it
    sql = "UPDATE note SET (date, note_text, pet_id, vet_id) = (%s, %s, %s, %s) WHERE id = %s"
    values = [note.date, note.note_text, note.pet.id, note.vet.id, note.id]
    run_sql(sql, values)