# Import needed modules
from database.run_sql import run_sql
from models.treatment import Treatment, PerscribedTreatment
import repositories.pet_repository as PR
import repositories.treatment_repository as TR

# CRUD Ops

# SAVE
def save(perscribed_treatment):
    # Create SQL query, pass in data && run
    sql = "INSERT INTO perscribed_treatment (pet_id, treatment_id) VALUES (%s, %s) RETURNING *"
    values = [perscribed_treatment.pet.id, perscribed_treatment.treatment.id]
    result = run_sql(sql, values)

    # Set the objects id to the id generated by db
    id = result[0]['id']
    perscribed_treatment.id = id
    return perscribed_treatment

# SELECT BY PET
def select_by_pet(id):
    # Create list of treatments == empty list
    treatments = []

    # Creat SQL query, input the values && run
    sql = "SELECT treatment.* FROM treatment INNER JOIN perscribed_treatment ON perscribed_treatment.treatment_id = treatment.id WHERE perscribed_treatment.pet_id = %s"
    values = [id]
    results = run_sql(sql, values)

    # Loop through results
    for row in results:
        # Create new object
        treatment = Treatment(row['name'], row['cost'], row['length'], row['medicine'], row['type'], row['id'])
        treatments.append(treatment)
    
    return treatments

# DELETE ALL
def delete_all():
    # Create SQL query && run
    sql = "DELETE FROM perscribed_treatment"
    run_sql(sql)