# Import needed modules
from database.run_sql import run_sql
from models.treatment import Treatment, PerscribedTreatment

# CRUD Ops

# SAVE
def save(perscribed_treatment):
    # Create SQL query, pass in data && run
    sql = "INSERT INTO perscribed_treatment (pet, treatment) VALUES (%s, %s) RETURNING id"
    values = [perscribed_treatment.pet, perscribed_treatment.treatment]
    result = run_sql(sql, values)

    # Set the objects id to the id generated by db
    id = result[0]['id']
    perscribed_treatment.id = id
    return perscribed_treatment

# SELECT BY PET
def select_by_pet(id):
    # Create list of treatments == empty list
    treatments = []

    # Creat SQL query, input the values && run
    sql = "SELECT treatment.* FROM treatment INNER JOIN perscribed_treatment ON perscribed_treatment.treatment_id = treatment.id WHERE perscribed_treatment.pet_id = %s"
    values = [id]
    results = run_sql(sql, values)

    # Loop through results