# Import required modules
from database.run_sql import run_sql
from models.classes import Pet, Owner, PetType
import repositories.pet_type_repository as PTR
import repositories.owner_repository as OR

# CRUD FUNCTIONS

# FUNCTION: save(item)
# This function is used to save a pet to the database
def save(pet):
    # Create the SQL query && input data before running it
    sql = "INSERT INTO pet (name, dob, owner_id, type_id) VALUES (%s, %s, %s, %s) RETURNING id"
    values = [pet.name, pet.dob, pet.owner.id, pet.pet_type.id]
    result = run_sql(sql, values)

    # Set the pet objects ID to the ID generated by the database
    pet.id = result[0]['id']
    return pet

# FUNCTION: select_all()
# This function is used to select all of the pets from the database and create python objects
# using the data so they can be displayed
def select_all():
    # Create list of pet objects and set == empty list
    pets = []

    # Create the SQL query && input data before running it
    sql = "SELECT * FROM pet"
    results = run_sql(sql)

    # Loop through all the results and append the objects to a list
    for row in results:
        # Get the objects to create the pet object
        pet_type = PTR.select(row['type_id'])
        owner = OR.select(row['owner_id'])

        # Create new pet object && append to pets list
        new_pet = Pet(row['name'], row['dob'], owner, pet_type, row['id'])
        pets.append(new_pet)

    return pets

# FUNCTION: select(item_id)

# FUNCTION: delete(item_id)