# Import needed modules
from database.run_sql import run_sql
from models.treatment import Treatment

# CRUD Ops

# SAVE
def save(treatment):
    # Create SQL query, pass in data && run
    sql = "INSERT INTO treatment (name, cost, length, medicine, type) VALUES (%s, %s, %s, %s, %s) RETURNING id"
    values = [treatment.name, treatment.cost, treatment.length, treatment.medicine, treatment.type]
    result = run_sql(sql, values)

    # Set the objects id to the id generated by db
    id = result[0]['id']
    treatment.id = id
    return treatment

# SELECT SPECIFIC
def select(id):
    # Create SQL query, input data && run
    sql = "SELECT * FROM treatment WHERE id = %s"
    values = [id]
    result = run_sql(sql, values)

    # If the result exists create an object to be returned
    if len(result) > 0:
        treatment = Treatment(result[0]['name'], result[0]['cost'], result[0]['length'], result[0]['medicine'], result[0]['type'], result[0]['id'])
    return treatment

# SELECT ALL
def select_all():
    # Create list of treatments == empty list
    treatments = []

    # Create SQL query, insert data && run
    sql = "SELECT * FROM treatment"
    results = run_sql(sql)

    # Loop through results
    for row in results:
        treatment = Treatment(row['name'], row['cost'], row['length'], row['medicine'], row['type'], row['id'])  
        treatments.append(treatment)

    return treatments      

# DELETE ALL
def delete_all():
    # Create the SQL query && run
    sql = "DELETE FROM treatment"
    run_sql(sql)